// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Y4iSFhhCvQ1O1GMrJzWt9MeZjweg_Ak',
    appId: '1:705913496943:web:16533d085de9ab95f9b49a',
    messagingSenderId: '705913496943',
    projectId: 'saucify-71787',
    authDomain: 'saucify-71787.firebaseapp.com',
    storageBucket: 'saucify-71787.appspot.com',
    measurementId: 'G-517RJZKXBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwpJcbHWH2MwGvlCL5N8rgpHmgwO6_138',
    appId: '1:705913496943:android:d7c14b451df79a1bf9b49a',
    messagingSenderId: '705913496943',
    projectId: 'saucify-71787',
    storageBucket: 'saucify-71787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6RTDXrN2wTvmS_tHOrRhgDGhPdfp9F7Y',
    appId: '1:705913496943:ios:91b539d6ba4ef6b2f9b49a',
    messagingSenderId: '705913496943',
    projectId: 'saucify-71787',
    storageBucket: 'saucify-71787.appspot.com',
    iosClientId: '705913496943-39fo71rr90h6ksf9pau628kl336qg06p.apps.googleusercontent.com',
    iosBundleId: 'com.example.saucify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6RTDXrN2wTvmS_tHOrRhgDGhPdfp9F7Y',
    appId: '1:705913496943:ios:91b539d6ba4ef6b2f9b49a',
    messagingSenderId: '705913496943',
    projectId: 'saucify-71787',
    storageBucket: 'saucify-71787.appspot.com',
    iosClientId: '705913496943-39fo71rr90h6ksf9pau628kl336qg06p.apps.googleusercontent.com',
    iosBundleId: 'com.example.saucify',
  );
}
